default: &default
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>

development: &development
  <<: *default
  database: casa_development

read_replica_development:
  <<: *development
  <%# username: readonly %>
  <%# need to setup a readonly user or can just use same connection %>

test:
  <<: *default
  database: app_workflow_test
